### ISSUE TITLE
LWORK and size(WORK,1) should match

### ISSUE THREAD

**Issue by MarDiehl** [marcdegraef/3Drotations#1]
https://github.com/marcdegraef/3Drotations/blob/e0f29f20ae7bdb113f3e2f491b05197648cefda0/src/f90/rotations.f90#L2438

This caused trouble for me
http://www.netlib.org/lapack/explore-html/d9/d8e/group__double_g_eeigen_ga66e19253344358f5dee1e60502b9e96f.html

**Comment by marcdegraef** [comment]
fixed

Closes #1
